"""Reusable runtime configuration for all agents in this project.

Design goals:
1) Keep provider/auth/model logic out of individual agent files.
2) Make it easy to add more agents that share the same environment behavior.
3) Fail fast with precise errors when env/auth is misconfigured.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv


SUPPORTED_PROVIDERS = {"vertex", "openai"}


@dataclass(frozen=True)
class AgentRuntimeConfig:
    """Normalized runtime config consumed by agent definitions.

    Attributes:
        provider: Selected model provider (`vertex` or `openai`).
        model: Concrete model string passed to `google.adk.agents.Agent`.
    """

    provider: str
    model: str


def _has_adc_credentials() -> bool:
    """Check whether ADC credentials are available for Vertex AI.

    We support both standard local-development auth paths:
    1) A service-account JSON path via `GOOGLE_APPLICATION_CREDENTIALS`
    2) User credentials generated by `gcloud auth application-default login`
    3) Non-file ADC sources (for example metadata server on GCE/GKE/Cloud Run)
    """

    service_account_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if service_account_path and Path(service_account_path).expanduser().exists():
        return True

    adc_path = Path.home() / ".config" / "gcloud" / "application_default_credentials.json"
    if adc_path.exists():
        return True

    # Fall back to the canonical Google auth resolver so non-file ADC
    # sources (metadata server/workload identity) are accepted.
    try:
        import google.auth

        credentials, _ = google.auth.default()
        return credentials is not None
    except Exception:
        return False


def _get_provider() -> str:
    """Read and validate provider selection from environment."""

    provider = os.getenv("AGENT_PROVIDER", "vertex").strip().lower()
    if provider not in SUPPORTED_PROVIDERS:
        raise RuntimeError("AGENT_PROVIDER must be either 'vertex' or 'openai'.")
    return provider


def _validate_vertex_requirements() -> None:
    """Validate required env/auth for Vertex execution.

    These checks run before any model call, so failures are explicit and immediate.
    """

    project = os.getenv("GOOGLE_CLOUD_PROJECT")
    location = os.getenv("GOOGLE_CLOUD_LOCATION")
    if not project or not location:
        raise RuntimeError(
            "Vertex AI requires GOOGLE_CLOUD_PROJECT and GOOGLE_CLOUD_LOCATION."
        )

    if not _has_adc_credentials():
        raise RuntimeError(
            "Vertex AI credentials were not found. Run "
            "`gcloud auth application-default login` or set "
            "GOOGLE_APPLICATION_CREDENTIALS to a service-account JSON key path."
        )


def _validate_openai_requirements() -> None:
    """Validate required env for OpenAI execution."""

    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OpenAI mode requires OPENAI_API_KEY to be set.")


def _configure_provider_environment(provider: str) -> None:
    """Set provider bridge env expected by Google ADK integrations.

    ADK/Gemini integrations use `GOOGLE_GENAI_USE_VERTEXAI` to route traffic.
    We set it deterministically from `AGENT_PROVIDER` so behavior is predictable.
    """

    os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "true" if provider == "vertex" else "false"


def configure_agent_runtime(
    *,
    default_model_by_provider: dict[str, str] | None = None,
) -> AgentRuntimeConfig:
    """Return validated runtime config used by any agent module.

    Args:
        default_model_by_provider: Optional override map for provider defaults.
            If omitted, defaults are:
            - vertex -> gemini-2.0-flash
            - openai -> gpt-4o-mini

    Returns:
        AgentRuntimeConfig with provider and resolved model name.
    """

    # Every agent can rely on this one place to load `.env`.
    load_dotenv()

    provider = _get_provider()
    _configure_provider_environment(provider)

    if provider == "vertex":
        _validate_vertex_requirements()
    elif provider == "openai":
        _validate_openai_requirements()

    defaults = default_model_by_provider or {
        "vertex": "gemini-2.0-flash",
        "openai": "gpt-4o-mini",
    }
    model = os.getenv("ADK_MODEL", defaults[provider])

    return AgentRuntimeConfig(provider=provider, model=model)
